name: SpringBoot_AWS S3,AWS API GateWay And AWS Lambda
on:
 push:
   branches: ["main","dev"]
 workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout from Repo
       uses: actions/checkout@v4.2.2
     - name: Install Java 21
       uses: actions/setup-java@v4.7.0
       with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
     - name: Build maven
       run: mvn clean install -DskiptTests=true
       working-directory: Spring_GitHubAction_AWS3_Lambda
       
     - name: Upload zip file
       uses: actions/upload-artifact@v4.6.1
       with:
        name: spring-aws-s3-lambda
        path: Spring_GitHubAction_AWS3_Lambda/target/*.zip   
